-- MySQL Script generated by MySQL Workbench
-- Wed Jul 10 19:10:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombres_Apellidos` VARCHAR(50) NOT NULL,
  `Correo_elextronico` VARCHAR(100) NOT NULL,
  `Usuario` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `Correo elextronico_UNIQUE` (`Correo_elextronico` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `Nombres_Apellidos` VARCHAR(45) NOT NULL,
  `Telefono` CHAR(9) NOT NULL,
  `Correo_Electronico` VARCHAR(100) NOT NULL,
  `Direccion` TEXT(45) NOT NULL,
  `DNI` CHAR(8) NOT NULL,
  PRIMARY KEY (`idClientes`),
  UNIQUE INDEX `Correo electronico_UNIQUE` (`Correo_Electronico` ASC) VISIBLE,
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Raza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Raza` (
  `idRaza` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRaza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sexo` (
  `idSexo` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_De_Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_De_Animal` (
  `idTipo_De_Animal` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_De_Animal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mascotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mascotas` (
  `idMascotas` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `F_Nacimiento` DATE NOT NULL,
  `Clientes_idClientes` INT NOT NULL,
  `Raza_idRaza` INT NOT NULL,
  `Sexo_idSexo` INT NOT NULL,
  `Tipo_De_Animal_idTipo_De_Animal` INT NOT NULL,
  PRIMARY KEY (`idMascotas`, `Clientes_idClientes`),
  INDEX `fk_Mascotas_Clientes_idx` (`Clientes_idClientes` ASC) VISIBLE,
  INDEX `fk_Mascotas_Raza1_idx` (`Raza_idRaza` ASC) VISIBLE,
  INDEX `fk_Mascotas_Sexo1_idx` (`Sexo_idSexo` ASC) VISIBLE,
  INDEX `fk_Mascotas_Tipo_De_Animal1_idx` (`Tipo_De_Animal_idTipo_De_Animal` ASC) VISIBLE,
  CONSTRAINT `fk_Mascotas_Clientes`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `mydb`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mascotas_Raza1`
    FOREIGN KEY (`Raza_idRaza`)
    REFERENCES `mydb`.`Raza` (`idRaza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mascotas_Sexo1`
    FOREIGN KEY (`Sexo_idSexo`)
    REFERENCES `mydb`.`Sexo` (`idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mascotas_Tipo_De_Animal1`
    FOREIGN KEY (`Tipo_De_Animal_idTipo_De_Animal`)
    REFERENCES `mydb`.`Tipo_De_Animal` (`idTipo_De_Animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado_Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado_Cita` (
  `idEstado_Cita` INT NOT NULL,
  `Estado_Cita` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado_Cita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Citas` (
  `idCitas` INT NOT NULL AUTO_INCREMENT,
  `Hora_Cita` CHAR(9) NOT NULL,
  `Estado_Cita` VARCHAR(50) NOT NULL,
  `Mascotas_idMascotas` INT NOT NULL,
  `Mascotas_Clientes_idClientes` INT NOT NULL,
  `Usuarios_idUsuario` INT NOT NULL,
  `Estado_Cita_idEstado_Cita` INT NOT NULL,
  PRIMARY KEY (`idCitas`, `Mascotas_idMascotas`, `Mascotas_Clientes_idClientes`, `Usuarios_idUsuario`, `Estado_Cita_idEstado_Cita`),
  INDEX `fk_Citas_Mascotas1_idx` (`Mascotas_idMascotas` ASC, `Mascotas_Clientes_idClientes` ASC) VISIBLE,
  INDEX `fk_Citas_Usuarios1_idx` (`Usuarios_idUsuario` ASC) VISIBLE,
  INDEX `fk_Citas_Estado_Cita1_idx` (`Estado_Cita_idEstado_Cita` ASC) VISIBLE,
  CONSTRAINT `fk_Citas_Mascotas1`
    FOREIGN KEY (`Mascotas_idMascotas` , `Mascotas_Clientes_idClientes`)
    REFERENCES `mydb`.`Mascotas` (`idMascotas` , `Clientes_idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Citas_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Citas_Estado_Cita1`
    FOREIGN KEY (`Estado_Cita_idEstado_Cita`)
    REFERENCES `mydb`.`Estado_Cita` (`idEstado_Cita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registro_De_Atencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registro_De_Atencion` (
  `idHistorial clinico` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Visita` DATE NOT NULL,
  `Hora` DATETIME NOT NULL,
  `Motivo_visita` TEXT NOT NULL,
  `Estado_Mascota` VARCHAR(150) NOT NULL,
  `Diagnostico_Generado` TEXT NOT NULL,
  `Tratamiento` VARCHAR(45) NOT NULL,
  `Observaciones` TEXT NOT NULL,
  `Citas_idCitas` INT NOT NULL,
  PRIMARY KEY (`idHistorial clinico`, `Citas_idCitas`),
  INDEX `fk_Registro_De_Atencion_Citas1_idx` (`Citas_idCitas` ASC) VISIBLE,
  CONSTRAINT `fk_Registro_De_Atencion_Citas1`
    FOREIGN KEY (`Citas_idCitas`)
    REFERENCES `mydb`.`Citas` (`idCitas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
